# Generated by Django 4.0.4 on 2022-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
